version: '3'

services:
  yvds-order-backend:
    image: yvds-backend
    build:
      context: Backend/OrderBackend
      dockerfile: Dockerfile
    environment:
      MS_SQL_CONNECTION_STRING: 'Server=yvds-database;Database=OrderDatabase;User=sa;Password=Geheim_101'
    ports:
      - 5050:80
    depends_on:
      -   yvds-sqlserver
    networks:
      -   yvds-network

  yvds-sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: yvds-database
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Geheim_101
    ports:
      - 1433:1433
    networks:
      -   yvds-network
  
  yvds-order-frontend:
    image: yvds-orderwebsite
    build:
      context: Frontend/OrderWebsite
      dockerfile: Dockerfile
    environment:
      API_BASE_URL: http://yvds-order-backend
    ports:
      - 5151:80
    depends_on:
      -   yvds-order-backend
    networks:
      - yvds-network

networks:
  yvds-network:
  
