version: '3'

services:
  yvds-order-backend:
    image: huminor.azurecr.io/yvds-dag20-orderbackend:1
    environment:
      MS_SQL_CONNECTION_STRING: 'Server=yvds-database;Database=OrderDatabase;User=sa;Password=Geheim_101'
    depends_on:
      -   yvds-sqlserver

  yvds-sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: yvds-database
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Geheim_101
  
  yvds-order-frontend:
    image: huminor.azurecr.io/yvds-dag20-orderwebsite:1
    environment:
      API_BASE_URL: http://yvds-order-backend
    ports:
      - 5151:80
    depends_on:
      -   yvds-order-backend
  
