trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Cuniculus/Cuniculus/*

variables:
  buildConfiguration: Release
  projectPath: Cuniculus.Cuniculus

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    displayName: build all
    inputs:
      command: 'build'
      projects: '$(projectPath)/**/*.csproj'
      arguments: '-c $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: run tests
    inputs:
      command: 'test'
      projects: '$(projectPath)/**/*.Test/*.csproj'
      arguments: '-c $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: create nuget package
    inputs:
      command: 'pack'
      packagesToPack: '$(projectPath)/**/*.csproj'
      nobuild: true
      versioningScheme: 'off'
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '$(projectPath)/**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: '743e2c69-63aa-426d-895c-02fc1ee82026/cbd6ff65-1137-4897-a6e3-477a48b11394'
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '743e2c69-63aa-426d-895c-02fc1ee82026/cbd6ff65-1137-4897-a6e3-477a48b11394'
      allowPackageConflicts: true